// Unified type definitions for pi-hybrid-memory — reconciles both pi-vcc and pi-observational-memory types
// ── VCC types ──

export type NormalizedBlock =
  | { kind: "user"; text: string; sourceIndex?: number }
  | { kind: "assistant"; text: string; sourceIndex?: number }
  | { kind: "tool_call"; name: string; args: Record<string, unknown>; sourceIndex?: number }
  | { kind: "tool_result"; name: string; text: string; isError: boolean; sourceIndex?: number }
  | { kind: "thinking"; text: string; redacted: boolean; sourceIndex?: number };

export interface SectionData {
  sessionGoal: string[];
  filesAndChanges: string[];
  commits: string[];
  outstandingContext: string[];
  userPreferences: string[];
  briefTranscript: string;
}


// ── OM types ──

export const OBSERVATION_CUSTOM_TYPE = "hybrid-memory.observation";

export type Relevance = "low" | "medium" | "high" | "critical";
// Memory handles generated by observer/reflector makeId(): 8-char base-36
// timestamp suffix + 4-char base-36 counter. This intentionally differs from
// Pi's native 8-character hex entry IDs, which identify source entries rather
// than recallable observations/reflections.
export const MEMORY_ID_PATTERN = /^[a-z0-9]{12}$/;

export interface ObservationRecord {
  id: string;
  content: string;
  timestamp: string;
  relevance: Relevance;
  sourceEntryIds?: string[];
}

export type LegacyReflection = string;

export interface ReflectionRecord {
  id: string;
  content: string;
  supportingObservationIds: string[];
  legacy?: boolean;
}

export type MemoryReflection = LegacyReflection | ReflectionRecord;

export interface MemoryDetailsV4 {
  type: "observational-memory";
  version: 4;
  observations: ObservationRecord[];
  reflections: MemoryReflection[];
}

export interface SourceProgress {
  sourceEntryId: string;
  nextOffset: number;
  totalLength: number;
}

export interface ObservationEntryData {
  records: ObservationRecord[];
  coversFromId: string;
  coversUpToId: string;
  tokenCount: number;
  sourceProgress?: SourceProgress;
}

// ── Branch Entry type (matches pi session entries) ──

export interface Entry {
  type: string;
  id: string;
  timestamp?: string;
  message?: unknown;
  content?: unknown;
  customType?: string;
  summary?: unknown;
  fromId?: string;
  data?: unknown;
  details?: unknown;
  firstKeptEntryId?: string;
}

export type SupportedMemoryDetails = MemoryDetailsV4;

// ── Type guards ──

export const isObservationEntryData = (v: unknown): v is ObservationEntryData =>
  !!v && typeof v === "object" && "records" in v && Array.isArray((v as ObservationEntryData).records);

export const isSupportedMemoryDetails = (v: unknown): v is SupportedMemoryDetails =>
  !!v && typeof v === "object" && "type" in v && (v as Record<string, unknown>).type === "observational-memory" && "version" in v && typeof (v as Record<string, unknown>).version === "number" && ((v as Record<string, unknown>).version as number) >= 3;

// ── Config types ──

export interface ExtensionConfig {
  overrideDefaultCompaction: boolean;
  debug: boolean;
}

export interface HybridSettings {
  observationThresholdTokens: number;
  observerChunkMaxTokens: number;
  observerEpochMaxTokens: number;
  compactionThresholdTokens: number;
  compactionThresholdPercentage: number | null;
  reflectionThresholdTokens: number;
  compactionModel: { provider: string; id: string } | null;
  transcriptLines: number;
  maxFiles: number;
  maxCommits: number;
  maxSummaryTokens: number;
}

export interface UnifiedConfig {
  extension: ExtensionConfig;
  hybrid: HybridSettings;
}

// ── Runtime ──

export type ResolveResult =
  | { ok: true; model: unknown; apiKey: string; headers?: Record<string, string> }
  | { ok: false; reason: string };
