// Unified type definitions for pi-hybrid-memory — reconciles both pi-vcc and pi-observational-memory types
import type { Api, Model } from "@earendil-works/pi-ai";

// ── VCC types ──

export type NormalizedBlock =
  | { kind: "user"; text: string; sourceIndex?: number }
  | { kind: "assistant"; text: string; sourceIndex?: number }
  | { kind: "tool_call"; name: string; args: Record<string, unknown>; sourceIndex?: number }
  | { kind: "tool_result"; name: string; text: string; isError: boolean; sourceIndex?: number }
  | { kind: "thinking"; text: string; redacted: boolean; sourceIndex?: number };

export interface SectionData {
  sessionGoal: string[];
  filesAndChanges: string[];
  commits: string[];
  outstandingContext: string[];
  userPreferences: string[];
  briefTranscript: string;
}


// ── OM types ──

export const OBSERVATION_CUSTOM_TYPE = "hybrid-memory.observation";

export type Relevance = "low" | "medium" | "high" | "critical";
// Memory handles generated by observer/reflector makeId(): 8-char base-36
// timestamp suffix + 4-char base-36 counter. This intentionally differs from
// Pi's native 8-character hex entry IDs, which identify source entries rather
// than recallable observations/reflections.
export const MEMORY_ID_PATTERN = /^[a-z0-9]{12}$/;

export interface ObservationRecord {
  id: string;
  content: string;
  timestamp: string;
  relevance: Relevance;
  sourceEntryIds?: string[];
}

export type LegacyReflection = string;

export interface ReflectionRecord {
  id: string;
  content: string;
  supportingObservationIds: string[];
  legacy?: boolean;
}

export type MemoryReflection = LegacyReflection | ReflectionRecord;

export interface MemoryDetailsV4 {
  type: "observational-memory";
  version: 4;
  observations: ObservationRecord[];
  reflections: MemoryReflection[];
}

export interface ObservationRetirement {
  observationId: string;
  reason: "exact-duplicate";
  preservedByObservationIds: [string];
  preservedByReflectionIds: [];
}

export interface ReflectionSupersession {
  reflectionId: string;
  supersededByReflectionId: string;
  reason: "strengthened";
}

export interface MemoryLifecycleDetailsV5 {
  type: "observational-memory";
  version: 5;
  generation: {
    inputFingerprint: string;
    parentMemoryCompactionId?: string;
  };
  reflectionsAdded: ReflectionRecord[];
  observationsRetired: ObservationRetirement[];
  reflectionsSuperseded: ReflectionSupersession[];
}

export type PersistedMemoryDetails = MemoryDetailsV4 | MemoryLifecycleDetailsV5;

export interface SourceProgress {
  sourceEntryId: string;
  nextOffset: number;
  totalLength: number;
}

export interface ObservationEntryData {
  records: ObservationRecord[];
  coversFromId: string;
  coversUpToId: string;
  tokenCount: number;
  sourceProgress?: SourceProgress;
}

// ── Branch Entry type (matches pi session entries) ──

export interface Entry {
  type: string;
  id: string;
  timestamp?: string;
  message?: unknown;
  content?: unknown;
  customType?: string;
  summary?: unknown;
  fromId?: string;
  data?: unknown;
  details?: unknown;
  firstKeptEntryId?: string;
}

const RELEVANCE_VALUES = new Set<Relevance>(["low", "medium", "high", "critical"]);

const isObservationRecord = (value: unknown): value is ObservationRecord => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  return typeof record.id === "string"
    && MEMORY_ID_PATTERN.test(record.id)
    && typeof record.content === "string"
    && record.content.length > 0
    && typeof record.timestamp === "string"
    && RELEVANCE_VALUES.has(record.relevance as Relevance)
    && (record.sourceEntryIds === undefined
      || (Array.isArray(record.sourceEntryIds)
        && record.sourceEntryIds.every(id => typeof id === "string" && id.length > 0)));
};

const isMemoryReflection = (value: unknown): value is MemoryReflection => {
  if (typeof value === "string") return value.length > 0;
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const reflection = value as Record<string, unknown>;
  return typeof reflection.id === "string"
    && MEMORY_ID_PATTERN.test(reflection.id)
    && typeof reflection.content === "string"
    && reflection.content.length > 0
    && Array.isArray(reflection.supportingObservationIds)
    && reflection.supportingObservationIds.every(id => typeof id === "string" && id.length > 0)
    && (reflection.legacy === undefined || typeof reflection.legacy === "boolean");
};

const isReflectionRecord = (value: unknown): value is ReflectionRecord =>
  typeof value !== "string" && isMemoryReflection(value);

const isReflectionSupersession = (value: unknown): value is ReflectionSupersession => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const supersession = value as Record<string, unknown>;
  return typeof supersession.reflectionId === "string"
    && MEMORY_ID_PATTERN.test(supersession.reflectionId)
    && typeof supersession.supersededByReflectionId === "string"
    && MEMORY_ID_PATTERN.test(supersession.supersededByReflectionId)
    && supersession.reason === "strengthened";
};

const isObservationRetirement = (value: unknown): value is ObservationRetirement => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const retirement = value as Record<string, unknown>;
  return typeof retirement.observationId === "string"
    && MEMORY_ID_PATTERN.test(retirement.observationId)
    && retirement.reason === "exact-duplicate"
    && Array.isArray(retirement.preservedByObservationIds)
    && retirement.preservedByObservationIds.length === 1
    && typeof retirement.preservedByObservationIds[0] === "string"
    && MEMORY_ID_PATTERN.test(retirement.preservedByObservationIds[0])
    && Array.isArray(retirement.preservedByReflectionIds)
    && retirement.preservedByReflectionIds.length === 0;
};

export const claimsMemoryDetailsVersion = (value: unknown, version: number): boolean => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const details = value as Record<string, unknown>;
  return details.type === "observational-memory" && details.version === version;
};

/** Read and isolate one known persisted memory-details record. */
export const readMemoryDetails = (value: unknown): PersistedMemoryDetails | undefined => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
  const details = value as Record<string, unknown>;
  if (details.type !== "observational-memory") return undefined;

  if (details.version === 3 || details.version === 4) {
    if (!Array.isArray(details.observations) || !details.observations.every(isObservationRecord)) {
      return undefined;
    }
    if (!Array.isArray(details.reflections) || !details.reflections.every(isMemoryReflection)) {
      return undefined;
    }
    return {
      type: "observational-memory",
      version: 4,
      observations: structuredClone(details.observations),
      reflections: structuredClone(details.reflections),
    };
  }

  if (details.version !== 5) return undefined;
  const generation = details.generation;
  if (!generation || typeof generation !== "object" || Array.isArray(generation)) return undefined;
  const generationRecord = generation as Record<string, unknown>;
  if (
    typeof generationRecord.inputFingerprint !== "string"
    || generationRecord.inputFingerprint.length === 0
    || (generationRecord.parentMemoryCompactionId !== undefined
      && (typeof generationRecord.parentMemoryCompactionId !== "string"
        || generationRecord.parentMemoryCompactionId.length === 0))
    || !Array.isArray(details.reflectionsAdded)
    || !details.reflectionsAdded.every(isReflectionRecord)
    || !Array.isArray(details.observationsRetired)
    || !details.observationsRetired.every(isObservationRetirement)
    || !Array.isArray(details.reflectionsSuperseded)
    || !details.reflectionsSuperseded.every(isReflectionSupersession)
  ) {
    return undefined;
  }
  return {
    type: "observational-memory",
    version: 5,
    generation: {
      inputFingerprint: generationRecord.inputFingerprint,
      ...(generationRecord.parentMemoryCompactionId
        ? { parentMemoryCompactionId: generationRecord.parentMemoryCompactionId as string }
        : {}),
    },
    reflectionsAdded: structuredClone(details.reflectionsAdded),
    observationsRetired: structuredClone(details.observationsRetired),
    reflectionsSuperseded: structuredClone(details.reflectionsSuperseded),
  };
};

// ── Type guards ──

export const isObservationEntryData = (v: unknown): v is ObservationEntryData =>
  !!v && typeof v === "object" && "records" in v && Array.isArray((v as ObservationEntryData).records);


// ── Config types ──

export interface ExtensionConfig {
  overrideDefaultCompaction: boolean;
  debug: boolean;
}

export interface HybridSettings {
  observationThresholdTokens: number;
  observerChunkMaxTokens: number;
  observerEpochMaxTokens: number;
  compactionThresholdTokens: number;
  compactionThresholdPercentage: number | null;
  reflectionThresholdTokens: number;
  compactionModel: { provider: string; id: string } | null;
  transcriptLines: number;
  maxFiles: number;
  maxCommits: number;
  maxSummaryTokens: number;
}

export interface UnifiedConfig {
  extension: ExtensionConfig;
  hybrid: HybridSettings;
}

// ── Runtime ──

export type ResolveResult =
  | { ok: true; model: Model<Api> }
  | { ok: false; reason: string };
